version: '2'

services:
    mongo:
        image: mongo
        container_name: assistant-mongo
        restart: always
        expose:
            - 27017
        volumes:
            - ${ASSISTANT_DATABASE_VOLUME}:/data/db

    golang:
        build: ./golang
        container_name: assistant-go
        restart: always
        working_dir: /go/src/github.com/iammordaty/assistant-backend
        environment:
            - TERM=xterm
            - DEBIAN_FRONTEND=noninteractive
        expose:
            - 80
        volumes:
            - ${ASSISTANT_BACKEND_VOLUME}:/go
            - ${ASSISTANT_COLLECTION_VOLUME}:/collection
        entrypoint: /entrypoint.sh

    php:
        build: ./php-fpm
        container_name: assistant-php
        restart: always
        working_dir: /data
        environment:
            - TERM=xterm
            - SLIM_MODE=${ASSISTANT_SLIM_MODE}
        expose:
            - 9000
        links:
            - mongo
            - golang:backend
        volumes:
            - ${ASSISTANT_FRONTEND_VOLUME}:/data
            - ${ASSISTANT_COLLECTION_VOLUME}:/collection
            - ./php-fpm/conf/php.ini:/usr/local/etc/php/php.ini

    nginx:
        image: nginx:latest
        container_name: assistant-nginx
        restart: always
        expose:
            - 80
        links:
            - php
        ports:
            - "8080:80"
        volumes:
            - ${ASSISTANT_FRONTEND_VOLUME}:/data
            - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
